"""added the school column in group DB

Revision ID: 2fff13c4c410
Revises: a6e4e4b13eda
Create Date: 2026-08-20 13:02:00.883371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fff13c4c410'
down_revision: Union[str, Sequence[str], None] = 'a6e4e4b13eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('school', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'school')
    # ### end Alembic commands ###
