"""check for some edits

Revision ID: 5d8e5a6dc44a
Revises: a4daedd07a13
Create Date: 2026-08-10 12:42:53.460805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8e5a6dc44a'
down_revision: Union[str, Sequence[str], None] = 'a4daedd07a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
