"""added the exams db and corrected professor to professor_id in users

Revision ID: 72329fa278f4
Revises: 2ad500a8bcb8
Create Date: 2026-09-01 09:59:43.771220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72329fa278f4'
down_revision: Union[str, Sequence[str], None] = '2ad500a8bcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('professor_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'professor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('professor', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'professor_id')
    # ### end Alembic commands ###
