"""Add authorized and first_visit columns

Revision ID: a4daedd07a13
Revises: b0c54e889d7b
Create Date: 2026-08-10 12:07:53.680180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4daedd07a13'
down_revision: Union[str, Sequence[str], None] = 'b0c54e889d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False, server_default=""))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default=""))
    op.add_column('users', sa.Column('first_visit', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index('unique_emails', 'users', ["email"], unique=True)
    #op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_visit')
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.drop_column('users', 'authorized')
    op.drop_index('unique_emails', "users")
    # ### end Alembic commands ###
