"""message to see in the commit

Revision ID: a6e4e4b13eda
Revises: 8e31bd7d657c
Create Date: 2026-08-18 01:13:50.998806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e4e4b13eda'
down_revision: Union[str, Sequence[str], None] = '8e31bd7d657c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """ op.alter_column('users', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)"""
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
